language: ruby
sudo: false
cache: bundler
env:
  - TRAVIS=true
branches:
  only:
    - 'master'
rvm:
  - 2.3.3
  - 2.2.6
  - 2.1.9
before_script:
  - "bundle install"
  - "git submodule init"
  - "git submodule update"
script: "bundle exec rake"
